query GetPosts {
  getPosts {
    id
    title
    content
    tag {
      id
      name
    }
  }
}

query GetPost {
  getPost(id: "a0a0a0a0-a0a0-a0a0-a0a0-a0a0a0a0a0a0") {
    id
    title
    content
    tag {
      id
      name
    }
  }
}

query GetTags {
  getTags {
    id
    name
  }
}

query GetPostsByTag($tagId: ID!) {
  getPostsByTag(tagId: $tagId) {
    id
    title
    content
    tag {
      id
      name
    }
  }
}

mutation CreatePost {
  createPost(newPost: { title: "Test Title", content: "Test Content", tagId: "someTagId"}) {
    id
    title
    content
    tag {
      id
      name
    }
  }
}

mutation DeletePost {
  deletePost(id: "a0a0a0a0-a0a0-a0a0-a0a0-a0a0a0a0a0a0") {
    id
    title
    content
  }
}

mutation UpdatePost {
  updatePost(id: "a0a0a0a0-a0a0-a0a0-a0a0-a0a0a0a0a0a0", newPost: {title: "updatedTitle", content: "updatedContent", tagId: "someTagId"}) {
    id
    title
    content
    tag {
      id
      name
    }
  }
}
